project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
  #   - "!about.qmd"
  #   - "!index.qmd"
  #   - "!cv.qmd"
    # - "!posts/post1.qmd"
    # - "!posts/vivaldi1.qmd"
    # - "!posts/search.qmd"
    # - "!posts/quarto.qmd"
    # - "!posts/rss.qmd"
    # - "!posts/login.qmd"
    # - "!posts/liveserver.qmd"
    # - "!posts/habit.qmd"

website:
  back-to-top-navigation: true
  favicon: "assets/favicons/favicon.ico" 
  page-footer:
    center: |
      Powered by <a href='https://quarto.org' target='_blank'>Quarto</a>
    right:
      - icon: rss
        href: blog_index.xml
        aria-label: Blog RSS feed
  open-graph: true
  site-url: "https://lukmayer.github.io"
  title: "Lukas W. Mayer"
  navbar:
    logo: "assets/favicons/android-chrome-512x512.png"
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: cv.qmd
        text: "CV"
      - href: blog_index.qmd
        text: "Blog"
      - href: about.qmd
        text: "About"
    right:
      - text: "[Login]"
        href: https://lukmayer.github.io/login_portal/
  
blog:
  title: "Luke's Blog"

format:
  html:
    code-line-numbers: true
    smooth-scroll: true
    theme: [darkly, theme-dark.scss]
    css: styles.css
    toc: true
    footnotes-hover: true
    reference-location: margin
    link-external-newwindow: true
    # link-external-icon: true
    link-external-filter: "https://www.lukmayer.github.io"
    canonical-url: true
    toc-location: left
    toc-title: "Sections:"
    toc-depth: 4
    toc-expand: 2
    title-block-style: manuscript
    title-block-banner: true
    title-block-banner-color: "#00bf63"
    title-block-categories: true
    code-fold: show
    code-copy: true
    code-tools: false
    code-overflow: scroll
    code-block-border-left: true
    highlight-style: atom-one
    fig-responsive: true
    lightbox: true
    
    

execute:
  cache: true
  freeze: auto


extensions:
  - animate
  
  
  