project:
  type: website
  output-dir: _site

website:
  favicon: "assets/favicons/favicon.ico" 
  page-footer: "Powered by <a href='https://quarto.org' target='_blank'>Quarto</a>"  
  open-graph: true
  site-url: "https://lukmayer.github.io"
  title: "<img src='assets/favicons/favicon.ico' alt='Logo' style='height:40px; vertical-align:middle;'>"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: cv.qmd
        text: "CV"
      - href: blog_index.qmd
        text: "Blog"
      - href: about.qmd
        text: "About"
    right:
      - icon: rss
        href: blog_index.xml
      - icon: envelope
        href: mailto:willuk@vivaldi.net
        aria-label: E-Mail
  
blog:
  title: "Luke's Blog"

format:
  html:
    smooth-scroll: true
    theme: [darkly, theme-dark.scss]
    css: styles.css
    toc: true

extensions:
  - copy-button
  
