---
title: "Curriculum Vitae"
---

### Lukas William Mayer
#### PhD student in Cognitive Science

\
\

### Contact Information

---

**Institutional Email**: <a href="mailto:lwmayer@uci.edu" target="_blank">lwmayer@uci.edu</a>

**Personal Email**: <a href="mailto:willuk@vivaldi.net" target="_blank">willuk@vivaldi.net</a>

**Lab Website**: <a href="https://steyvers.socsci.uci.edu/madlab/" target="_blank">Modelling and Decision-making Lab</a>

**Personal Website**: <a href="https://lukmayer.github.io" target="_blank">https://lukmayer.github.io</a>


\
\


### Education 

---

#### **PhD in Cognitive Science, 2028 (Expected)**

*University of California, Irvine, Irvine, CA, USA*

**Thesis (preliminary title)**: “Computational modelling of inversion problems in human-AI interaction”

**Advisor**: Prof. Mark Steyvers

Focus on Bayesian modelling of human problem-solving abilities and alignment of AI systems with human cognition

\

#### **MSc in Behavioural and Data Sciences (Distinction), 2022**

*University of Warwick, Coventry, England, UK*

**Thesis**: “Cognition-Inspired Heuristics Improve Machine-Learning Predictions in Multi-Attribute Multi-Alternative Choice”

**Advisor**: Prof. Nick Chater

Focus on unifying models from computational cognitive science and machine learning

\

#### **BSc (Hons) in Psychology (First-Class), 2021**

*University of Stirling, Stirling, Scotland, UK*

**Thesis**: “Cooperation does not improve selective and/or sustained attention”

**Advisors**: Dr. John Michael and Dr. Ross Goutcher

Focus on measuring cognitive abilities in online games

\
\


### Research Experience 

---

#### **Research Assistant: Centre for Research and Evidence on Security Threats (CREST) 2022 - 2023**

*University of Bath, School of Management, Bath, England, UK*

Working within the Applied Digital Behaviour Lab on large-scale mixed methods study concerned with the prediction of online group communications which translate into real-world actions.

**Principal Investigator**: Prof. Adam Joinson

\

#### **Research Assistant: Centre for Cognition in Complex Environments 2019- 2021**

*University of Stirling, Department of Psychology, Stirling, Scotland, UK*


Working within the ConFace Lab on projects around face matching and concealed identity recognition

**Principal Investigator**: Dr. Ailsa E. Millen

\

#### **Research Assistant: Centre for Cognition in Complex Environments 2021**

*University of Stirling, Department of Psychology, Stirling, Scotland, UK*

Working within the Learning & Memory Lab on automated video analysis for discrimination learning in lumpfish

**Principal Investigator**: Dr. Jamie Murray

\
\

### Publications 

---

Karny, S., **Mayer, L. W.**, Ayoub, J., Song, M., Su, H., Tian, D., Moradi-Pari, E., & Steyvers, M. (2024). Learning with AI Assistance: A Path to Better Task Performance or Dependence? *Proceedings of the ACM Collective Intelligence Conference, 10–17*. https://doi.org/10.1145/3643562.3672610

\

Steyvers, M., Tejeda, H., Kumar, A., Belem, C., Karny, S., Hu, X., **Mayer, L. W.**, & Smyth, P. (2024). The Calibration Gap between Model and Human Confidence in Large Language Models. arXiv preprint arXiv:2401.13835.

\

**Mayer, L. W.**, Bocheva, D., Hinds, J., Brown, O., Piwek, L., Ellis, D. (under Review) Waste not want not: Computational methods to maximise attendance in group research. *Behavior Research Methods*.

\
\

### Awards and Honors 

---

**Best Overall Score: Behavioural and Data Science (2022)**

\

**Peter McEwan Prize for the Best Single Honours Psychology Student (2021)**

\

**Alan Baddeley Prize for the Best Psychology Dissertation (2021)**

\

My Stirling Award (GOLD) for acquiring an exceptional depth and breadth of extracurricular achievements (2021)

\

Honourable Mention for the Best Psychology Placement Student (2021)

\
\

### Other Activities 

---

**Digital Methods Initiative Winter School - The use and misuse of Open Source Intelligence, 2023**

*University of Amsterdam, Amsterdam, North Holland, The Netherlands*

\

**International Interdisciplinary Computational Cognitive Science Summer School, 2022**

*University of Tübingen, Tübingen, Baden-Württemberg, Germany*

\

**NeuroMatch Academy Summer School: Deep Learning, 2022**

*NeuroMatch Academy, Los Angeles, CA, USA*


