---
title: "Research"
format:
  html:
    smooth-scroll: true
---

\

## Research Interests

### 1) Computational Cognitive Science
{{< animate fadeIn "As humans, we possess a remarkable cognitive flexibility that enables us to solve problems in various domains that are still completely intractable to modern methods in Artificial Intelligence. Therefore, I think that by studying human behavior we may be able to reverse-engineer some of the machinery that gives rise to these amazing abilities, paving the way for new kinds of algorithms."  duration=4s >}}

{{< animate fadeIn "At the moment, I am working on a project series aiming to develop a computational account of causal reasoning for intervention on other agents. In these projects I will be using a considerable amount of simulation, computational modelling, and a series of custom-designed web experiments to develop reasoning models that exhibit human-like abilities to flexibly generalize to new contexts. My goal here is to show how this causal account can outperform sophisticated Reinforcement Learning models in dynamic environments, which includes most of the real world."  duration=4s delay=1s >}}


\

### 2) Inversion problems in Cognitive Science
{{< animate fadeIn "Whenever people are interacting with machine-learning based systems, (human) biases can propagate through the model leading to distorted predictions. Therefore, one strand of work I am interested in pursuing in this area is to derive the transformations that lead to better alignment, thus increasing the validity of predictions. I am also interested in addressing more engineering related concerns, such as how to use information we possess about cognition to improve the performance of machine learning algorithms trained on human-generated information. In this type of work, I like to mix and match methods from Cognitive Science and Machine Learning in combination with large, real-world data-sets."  duration=4s delay=2s >}}

{{< animate fadeIn "One fairly recent project I have completed in this domain was my master’s thesis. In it, I was able to show how re-weighting a feature space in line with some theory borrowed from multi-attribute multi-alternative decision-making can improve the performance of machine learning algorithms tasked with predicting human choices."  duration=4s delay=3s >}}



\


<div id="embedded-publications"></div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    fetch('cv_lwm.html') // Adjust the path to your CV page as needed
      .then(response => response.text())
      .then(data => {
        const parser = new DOMParser();
        const doc = parser.parseFromString(data, 'text/html');
        const publicationsSection = doc.querySelector('#publications');
        document.getElementById('embedded-publications').innerHTML = publicationsSection.innerHTML;
      });
  });
</script>

