---
title: "Now"
description: "What I'm up to right now"
format: 
  html:
    grid:
      margin-width: 300px
---

# 2025





## 2025-05-01

First post! 

Currently piloting a study that's all about giving rise to AI assistants that are not annoying to people. I have an experiment going that's meant to inform a cognitive model which in turn will inform a POMDP model. It's really exciting! 

The experiment is written in Pygame, which it turns out can be web-hosted with some extra steps. You can inject Javascript too! It's pretty neat because I can now just work with a language I know and love. 

The other thing maybe worth mentioning is that I'm taking a Stats course on Longitudinal Data Analysis. 

In a few weeks time, I'll take a Data analysis exam, which forms part of the Stats MS I want to do alongside this PhD... 

Finally, currently trying to figure out what to do with my summer! I'll be heading to Japan (and Taiwan) towards the end of the break but should also really show my face in UK again and see my family in Germany.

