---
description: "What I'm up to right now"
format: 
  html:
    toc-depth: 4
    toc-expand: 4
    grid:
      margin-width: 300px
---

# Now

## 2025

### 2025-08-16

Yet another re-theme for my website - I "hacked" the Bootstrap Brite theme to make it compatible with my Quarto site. It was a lot of tinkering and there are still some fixes I need to add but overall I'm pretty pleased with the minimal yet opinionated look! Other news include me intentionally killing my 2300+ day Duolingo streak and my imminent Japan + Taiwan trip - I'm stoked! 

\

### 2025-07-18

Back from Europe! Pretty excited to keep plugging away at my 'Annoying AI' project, for which I will be presenting a poster at this year's CogSci conference! I will also be attending ACM's Collective Intelligence conference since San Diego is close-by :)

\

### 2025-06-11

I'm currently in the midst of re-designing my site. Until very recently, I was using dark mode very religiously, but I have now seen the light. Therefore, a redesign. Also, to simplify my CSS a bunch.

I've booked all my travel: a weekend in London, 10 days in Germany, a month of Asia involving Japan and Taiwan. This would be my first time outside "the West"!

Not entirely sure how that last stretch of travel will play out given some of the political turbulences at the moment. Hoping for the best!

\

### 2025-05-01

First post! 

Currently piloting a study that's all about giving rise to AI assistants that are not annoying to people. I have an experiment going that's meant to inform a cognitive model which in turn will inform a POMDP model. It's really exciting! 

The experiment is written in Pygame, which it turns out can be web-hosted with some extra steps. You can inject Javascript too! It's pretty neat because I can now just work with a language I know and love. 

The other thing maybe worth mentioning is that I'm taking a Stats course on Longitudinal Data Analysis. 

In a few weeks time, I'll take a Data analysis exam, which forms part of the Stats MS I want to do alongside this PhD... 

Finally, currently trying to figure out what to do with my summer! I'll be heading to Japan (and Taiwan) towards the end of the break but should also really show my face in UK again and see my family in Germany.

