---
title: "Why is nature so disturbing?"
description: "On overthinking animal documentaries and human exceptionalism"
author: "Luke"
date: "2025-05-04"
categories:
 - uncategorized

comments:
  giscus:
    repo: lukmayer/site_comments
    theme: dark
    mapping: url
    reactions-enabled: true
---

Why is it that I find the more gruesome scenes in nature documentaries so hard to watch, when I myself am an animal? A meat-eating animal at that. Why do I notice a reaction that seems to reject the axioms of natural selection, a system I cannot opt out of? This internal hypocrisy has been puzzling me a bit as of late.

As my wording may have already implied, one convenient and intuitive explanation for the reaction I observed within myself comes from the fact that my brain can't help but feel the pain of the prey animal featured in the documentary. But I actually think that there is more to it than just empathy. 

Perhaps part of that reaction could stem from the fact that we operate in rules-based systems and so live largely removed from mortal violence. We have devised elaborate procedures to ensure relatively fair outcomes for everyone (it's definitely still work in progress). Remind yourself, the animal kingdom does not have courts, insurance, healthcare, or institutionalized social safety. These are all human inventions because we do not like the alternative. So I think part of the gut reaction arises from the unexpected reminder that the default system in nature is one free of safety, justice, and any sense of certainty. 

Of course, we also choose ignorance. When was the last time you had to provision your own meat? Few of us can say to have ever gone through the full process. The anonymous meat package from the supermarket removes us wholly from the fact that we still operate within the sometimes brutal bounds of nature, whether we like it or not. Maybe one day we can all successfully do without animals for food, but for now we still largely live like predators so sophisticated that they have forgotten how to hunt. 

The question I want to ask though, is whether this rejection of where we come from is an asset or a risk? As you may be able to tell, I currently hold that it's a bit of both.

Arguing against our hubris is straightforward. Of course we should not forget where we come from. When it really comes down to it, we are just like any other animal fighting for survival. We are not special and our societies are not special either. History tells us that the rules we like so much are actually very fragile, and can be undone in a heartbeat. We must not forget that we are not above nature, simply part of it. The relative stability many of use live in today requires constant maintenance, and we must not take it for granted.

On the other hand, I think it's interesting that we collectively seem to have this internal drive to create societies with special properties that we deem desirable. Ones where altruistic behaviors extends far beyond kinship, or any sort of personal relationship. For example, the nameless bureaucrat signing off your insurance claim has no interest in you whatsoever, probably has never met you, and yet they are technically doing you a significant favor. Over millenia, we have tinkered on how to organize ourselves in a way that allows us to live together in relative peace and prosperity. So in a really weird way, the fact that you do not really know where your supermarket meat came from shows that you are part of a system that has offered you the luxury of not having to know[^1]. Maybe the fact that we are so pampered allows us to think about where to take things next? We never feel that we have arrived at an optimal state. After all, worrying about some of our marginalized groups of today would probably have been unthinkable to someone who lived even just a few hundred years ago. 

[^1]: I want to be clear here to say that I do not believe that one should pride themselves on being ignorant about where their food comes from. We'd be a lot better off if everyone was making more informed decisions. I'm simply observing where I think that ignorance comes from.

So in sum, we ought to remember that the default state of things is something like what we see in nature documentaries, and that resisting a return to such circumstances requires constant and continuous effort due to our self-destructive tendencies. At the same time, we ought not to only look back, but also forward, so that we can continue to work towards a better future. Maybe with all of this in mind, I'll be better prepared for the next time I see a lion approaching an unsuspecting gazelle...

I hope you found this little trail of thoughts interesting. 
















