---
title: "Have we reached maximum click-bait yet?"
description: "My struggle with social media"
author: "Luke"
date: "2025-05-11"
categories:
 - social media

comments:
  giscus:
    repo: lukmayer/site_comments
    theme: dark
    mapping: url
    reactions-enabled: true
---


I've never been much into social media. There was a period where I used Instagram to follow my friends and artists I liked. Facebook I only used very briefly as an undergrad. Technically, I still have a Linkedin account that receives no attention from me. However, even back in my social media days I noticed the tendency of these platforms to show you stuff that will grab your attention whether you like it or not.


Since then, I've been exploring Fediverse platforms like Mastodon and Lemmy. But all  platforms I have tried have this same problem of incentivizing what I would call rage- or click-bait[^1]. The problem I have with these phenomena is that they are cheap, ubiqutous signals that serve to manipulate. An attention-grabbing essay title that does not follow the click-bait format is really different in this regard, as an interesting title at least has some correlation to the quality of the writing. 


Essentially, I don't think popularity metrics are very useful for distinguishing between quality (where engagement comes through resonance with the audience) and rage-bait (where engagement comes from tricking people into boosing the metrics).
I have a feeling that platforms which serve to make content creation as easy as possible will never be able to solve this, as accessibility necessarily induces more low-quality content. In other words, short-form text, photos, and video clip producers will always be incentivized to click-bait[^2]. 


[^1]: I use these terms fairly liberally to basically encapsulate anything that is tailor-made to be attention-grabbing, like using very strong wording or misleading images.  


[^2]: Academia has a similar problem, since how many papers you publish is far more important for your career than how "good" those papers are. The quality metric, citations, is deeply flawed too. At least university departments put in a bit of effort to look at your papers before inviting you to interview, assuming of course you made it to the stage where they check.


I should say though, Mastodon can be made sane. It is up to you though. This is because Mastodon allows you to hide posts that contain keywords of your choosing. So you can maintain a list of keywords you classify as rage-baity in nature and so only see the stuff that's left after that. Of course, that requires some effort, continuous vigilance, and being ok with never seeing the false positives. If you want to use Mastodon, I would generally recommend being pretty liberal in your use of filter words.


How to stop gaming of metrics? Simple, have no metrics. The problem of course is that noone would find a "Trending" tab that really is just a "Random" tab very worthwhile. "Popular" content is used to on-board new users and popularity is also used to make decisions about what to recommend. Ironically, a social media platform that does away with inadvertedly incentivizing garbage by default would never be accessible enough to have main-stream appeal.


Is any of this unique to social media? Of course not. We could easily think of news outlets increasingly following a similar recipe. These trends towards maximum click-bait make me a bit worried about where democracies are headed, especially now with AI making influence campaigns nigh fully automatable. Until we have found a good way to address these problems, it's probably best you make sure you control what stuff is on your feed, and help your friends do the same. 




