---
title: "Is it even possible to avoid big-tech?"
description: "A status update on my tech experiment"
author: "Luke"
date: "2025-05-18"
categories:
 - software

comments:
  giscus:
    repo: lukmayer/site_comments
    theme: dark
    mapping: url
    reactions-enabled: true
---

Have you ever had a thought that goes something like "Do I really need \<something\>"? I definitely have. Over the years, I have done some silly multi-week experiments to assess things like: what would it be like to sleep without a pillow, live without a mirror, work without a chair. Why? Just to challenge my habits, I think.

Currently, I guess I have two experiments going on: growing my hair out fairly long, and doing without "big-tech". Obviously, the latter one is what this post is about.

The motivation for this experiment goes something like: Why does everyone use the same software? 
If you think about it, for PC operating systems you get a choice of macOS (Apple), Windows (Microsoft); for phones you get iOS (Apple), and Android (Google); for apps, it's either Apple's App Store, or the Google Play Store; for browsers you only really get Chrome (Google) with Google as the search engine. Most normal people either use Google Drive or OneDrive (Microsoft). Productivity apps either come in the form of Microsoft 365 or Google's App suite. For E-mail everyone has a Gmail account and most will also have an Outlook (Microsoft). Messaging is done on either iMessage (Apple), WhatsApp (Meta), Messenger (Meta, again). Social media is mostly stuff owned by Meta, with LinkedIn owned by Microsoft. There's probably more one could add to the list... The point is, is it really necessary to operate in a tech ecosystem where every niche seems to be some kind of de facto mono/duo/oligopoly[^1] involving a random choice from the same four (-ish) companies?

[^1]: I write "de facto" because determining the monopoly status of these companies is evidently quite difficult under current competition law. 

I didn't know I was going to embark on this experiment at the time, but technically my journey started by wondering if Chrome was really serving me all that well. I remember finding Google products frustrating because they never really offered any settings to tweak. Of particular annoyance to me at the time was that many Google products lacked a dark mode setting. Sometimes the settings page of these apps felt more like an empty placeholder accidentally left in rather than the polished product of some billion-dollar company. Why was Google assuming that all of their billions of users used their products exactly the same way? I wasn't that committed to using Chrome, so I shopped around. My initial browser switch was to Opera, which was pretty customizable compared to Chrome then (still is).

Microsoft products were typically much more customizable than Google's offerings, so for a while I considered myself a Microsoft fan. Besides Windows, I was using Outlook, OneNote, Word, Excel, PowerPoint, OneDrive, even their dedicated To-Do app and Android Launcher. That only really started to change when Windows 11 rolled out, where seemingly all options had been stripped away, with annoyances now impossible to turn off. It drove me nuts, so I decided to try Ubuntu. Linux definitely is something one needs to get used to because it can uproot so much of an average person's software stack. However, once I adjusted I never felt it worth going back. Thankfully, most things are web-based nowadays, so as long as you have a browser a normal person can be just fine.

These days, I really only have a few things left that have proven very sticky.
For some things, my hands are simply tied. For example, my university compels me to use Gmail and Microsoft Teams for my work. If it wasn't for that my only use of Google products would be Google Voice because I have a VoIP number that I don't want to pay monthly for, and the Google Play Store because commercial apps are not put anywhere else. As a partial remedy, I generally use F-droid wherever I can or just use services on Desktop (where there usually is much more choice) instead of my phone. Social media is also surprisingly sticky; I still don't find myself able to delete WhatsApp because it's so ubiquitous in Europe and I also technically still have a LinkedIn account[^2]. 

There is also stuff that I could do without but in practice do not. 
I use Google Scholar and GitHub pretty regularly, this very website is currently hosted on GitHub. My research data goes to a Google Firebase database. Academic search engines are few and far between, although I may want to give Semantic Scholar another shot. Hosting on GitHub and using Firebase means not having to pay for a service that would usually cost money. I would love to self-host but can't do that at the moment as I live on campus and so have no control over my network. 

[^2]: I think I have a vague sense of it potentially being helpful for a future job search. Although I can't say I have ever found a job through LinkedIn. 

So yes, in principle it is still possible to avoid large parts of the big-tech ecosystem, although only with some notable caveats. For one, it took me the better part of 3 years to slowly transition away. I think switching E-mails nicely paints the problem. You are free to choose any E-mail service you like, but if you have a Gmail you can use it to log in to all kinds of services, and as you start using this Gmail to register for various things, it becomes more and more effortful to move all of those things to a different, non-Gmail account. In other words, it takes a serious, prolonged effort to abstain from big-tech services. And even if you have the will, chances are someone else will still compel you to use some big-tech provisioned services. It was only a few months ago where an academic journal obliged me to use ***Premium*** Adobe Acrobat Reader to fill out a form that was so bare-bones it could just as well have been a simple text file. I should also mention that some of the stuff I ended up using is still heavily dependent on big tech. For example, most browsers are built on the Chromium open source project, managed by Google[^3]. 


[^3]: Similarly, Android alternatives are typically made from Google's Android Open Source Project.

Is abstaining even worth it? In some ways, maybe yes. I pay fewer subscriptions than I used to. I don't have to deal with ads or other "features" being shoved down my throat. In other ways, for many people, not really. For example, Linux undeniably has some jankiness that makes it hard(er) to use in many everyday settings than other operating systems. I don't see myself going back though because I value the freedom to set it up to whatever I like highly and don't mind occasional use of the terminal.


I wonder what these things will be like in 10–20 years? Will it be yet more of the same with additional domains monopolized, will big companies maybe have been split up in a way that is actually productive for sustained competition, or will some kind of massive libre software revolution suddenly materialize out of thin air? On the one hand, I get the sense that software is more vulnerable to de facto monopolies compared to industries that operate in the material world[^4], so I do think this phenomenon of specific niches being utterly dominated by one or two big companies is unlikely to go away completely. On the other hand, it does also feel like more and more people are holding views according to which some types of software should be considered public goods and managed as such. It will definitely be interesting to see which path we end up going down. 

[^4]: Because of increased potential to benefit from virality, popularity- and network effects.








