---
title: "Bread in the USA"
description: "Andere Länder, andere Sitten"
author: "Luke"
date: "2025-05-02"
categories:
 - phd
 - life

comments:
  giscus:
    repo: lukmayer/site_comments
    theme: dark
    mapping: url
    reactions-enabled: true
---

I don't mean to complain too much about what my life is like in the USA.

- The weather here in California is always monotonically pleasant
- Americans are super friendly, welcoming, and helpful
- My university is excellent
  - My workplace is unionized
  - My rent is heavily subsidized, housing is guaranteed
  - My department is full of excellent researchers
  - Even my grad student health insurance is good, in 2 years I have never spent more than $80 on a procedure

  Of course, we could reflect on whether my list reflects the average experience of Americans, or even American graduate students. But that's not the point here.


  The point is, things are good. I'd even say they are great. I am very happy and grateful for the life I have here.

  But, as a German, there is one thing that I can't seem to get over. And that is American's taste in baked goods, especially bread.


  This was already a problem when I lived in the UK, so maybe Anglo-Saxon countries are just genetically-wired to be problematic to me in this regard.

  In the UK, while bread may have been a bit soulless here and there, it was always possible to find something that I felt was edible, even at the supermarket. 

  Over here, the choice seems to be between a) full of sugars and additives, or b) completely void of everything, including taste. I even tried going to a farmer's market to see what the fancy people are eating. But even there, the breads looked less interesting than some of the stuff I was able to dig out of UK supermarkets.

  Germans in the UK really like to complain about the bread in the UK. To be honest, the gap between UK and US is much larger than the gap between UK and Germany.

  Is there a fancy artisan bakery somewhere in Orange County that might be able to help me out? Probably. I feel like driving for 20+ minutes in one of the largest Metro regions of the USA shouldn't be necessary for a nice household staple but maybe that's just me. In practice, I am stuck with what I can reach by foot, bike, bus, or can get delivered. 

  So in conclusion, I have been pondering just taking the hit and baking the bread myself.
  I don't think I'm desperate enough quite yet, but if you see me posting about sourdough starters in a few weeks, you'll know I'll have finally snapped.




