---
title: "Blackboard"
format:
  html:
    callout-appearance: default
---

::: {.quarto-content .hidden}
:::

```{=html}
<style>
.description {
    display: none;
}
</style>
```

```{=html}
<script>
  window.addEventListener("load", function() {
    var content = document.querySelector(".quarto-content");
    if (content) {
      content.classList.remove("hidden");  // Remove the hidden class to allow transition
      content.classList.add("fade-in");    // Add the fade-in class for the transition effect
    }
  });
</script>
```

::: column-page
<iframe src="blackboard.html" width="100%" height="800px" allowfullscreen>

</iframe>
:::

```{=html}
<style>
.callout-title-container {
    font-size: 1.2rem;
}

.callout-title-container strong em {
    font-size: 1.5rem;
}


/* Title block background */
.callout-header {
    background-color: #222222 !important;  /* Light gray */
}

/* Main text area background */
.callout-body-container {
    background-color: #111111;  /* dark gray */
}

/* Optional: if you want to style the entire callout container */
.callout {
    border: 1px solid #dee2e6;  /* Light border */
}

/* change the drop-down arrow */
.py-1 {
    padding-top: .25rem !important;
    padding-bottom: .25rem !important;
    scale: 2;
}

div.callout-important.callout {
    border-left-color: #5f5f5f;
}

</style>
```

Don't like the embedded blackboard? [Open it in a new tab](blackboard.html){target="_blank"}.

---

::: {.callout-important collapse="true" icon="false"}
# What is this?

This is a blackboard you can draw on.
You can even save the drawings you made here to a file on your computer.
I don't store any of the drawings you make here.
:::

::: {.callout-important collapse="true" icon="false"}
# Why did you make this?

Every now and then I just want to quickly draw something to explain a concept.
I felt like having a tool for this on my site would be cool, and pretty easy to reach in a pinch.
:::

::: {.callout-important collapse="true" icon="false"}
# How did you make this?

Technically, this is a Reveal.js presentation that is embedded on this page with an iframe.
The blackboard is an Excalidraw plugin that is part of the Reveal.js presentation.
This was simply the first idea I had for implementing this quickly; not claiming this is the best way to do it. I added some JavaScript to be able to toggle the blackboard on mobile devices.
:::

