---
title: "Research Interests"
description: "Lukas Mayer's research in computational cognitive science, Human-AI collaboration. Related topics include causal reasoning, inversion problems, AI alignment, data-science, software development"

---
<style>
.description {
    display: none;
}
</style>

<script>
  window.addEventListener("load", function() {
    var content = document.querySelector(".quarto-content");
    if (content) {
      content.classList.remove("hidden");  // Remove the hidden class to allow transition
      content.classList.add("fade-in");    // Add the fade-in class for the transition effect
    }
  });
</script>

:::{.column-body-outset}

::: {.animate__animated .animate__fadeIn}


### 1) Computational Cognitive Science

People possess a remarkable cognitive flexibility enabling us to solve problems in various domains that are still completely intractable to modern methods in Artificial Intelligence. Therefore, I think that by studying human behavior we may be able to reverse-engineer some of the machinery that gives rise to these amazing abilities, uncovering the structure that may pave the way for new kinds of algorithms.

At the moment, I am working on a project series aiming to develop a computational account of causal reasoning for intervention on other agents. In these projects I will be using a considerable amount of simulation, computational modelling, and a series of custom-designed web experiments to develop reasoning models that exhibit human-like abilities to flexibly generalize to new contexts. My goal here is to show how this causal account can outperform sophisticated Reinforcement Learning models in dynamic environments, which includes most of the real world.


\

### 2) Inversion and Alignment problems in Cognitive Science & AI

Whenever people are interacting with machine-learning based systems, human biases can propagate through the model leading to distorted predictions. Therefore, one strand of work I am interested in pursuing in this area is to derive the transformations that lead to better alignment, thus increasing the validity of predictions. I am also interested in addressing more engineering related concerns, such as how to use information we possess about cognition to improve the performance of machine learning algorithms trained on human-generated information. In this type of work, I like to mix and match methods from Cognitive Science and Machine Learning in combination with large, real-world data-sets.

Some of my recent work in this area can be broadly described with the umbrella term of "Human-AI collaboration". AI technologies are increasingly being integrated into various tools, but they oftentimes lack the ability to anticipate the needs of the human user. Using formal models of human cognition as part of these systems can help bridge this gap by describing mental processes people have in a language that AI systems can understand (math). This can lead to more efficient and effective collaboration between humans and AI systems, and can also help to identify potential pitfalls in the design of these systems.  


\

:::{.text-center}

<a href="../publications/index.qmd" class="button">Check out my current publications</a>

<style>
.button {
  display: inline-block;
  padding: 10px 20px;
  font-size: 16px;
  font-weight: bold;
  color: #00a653;
  background-color: #333333;
  text-align: center;
  text-decoration: none;
  border-radius: 5px;
  transition: background-color 0.3s ease;
}

.button:hover {
  background-color: #444444;
}
</style>

:::

:::
:::